'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ibis_megastudy_pilot.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = Value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property done() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("done", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eye() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eye", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version = &apos;1.0&apos; encoding = &apos;utf-8&apos;?&gt;
        '''&lt;survey&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;starttime&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;vdate&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldname = &apos;clinicianid&apos; fieldtype = &apos;text&apos;&gt;
        '''		&lt;text&gt;Clinician ID&lt;/text&gt;
        '''		&lt;maxCharacters&gt;80&lt;/maxCharacters&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldname = &apos;clinicianid2&apos; fieldtype = &apos;text&apos;&gt;
        '''		&lt;text&gt;Clinician ID&lt;/text&gt;
        '''		&lt;maxChar [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property hiv_lab() As String
            Get
                Return ResourceManager.GetString("hiv_lab", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version = &apos;1.0&apos; encoding = &apos;utf-8&apos;?&gt;
        '''&lt;survey&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;starttime&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;vdate&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldname = &apos;clinicianid&apos; fieldtype = &apos;text&apos;&gt;
        '''		&lt;text&gt;Clinician ID&lt;/text&gt;
        '''		&lt;maxCharacters&gt;80&lt;/maxCharacters&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldname = &apos;clinicianid2&apos; fieldtype = &apos;text&apos;&gt;
        '''		&lt;text&gt;Clinician ID&lt;/text&gt;
        '''		&lt;maxChar [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property htn_clinic() As String
            Get
                Return ResourceManager.GetString("htn_clinic", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version = &apos;1.0&apos; encoding = &apos;utf-8&apos;?&gt;
        '''&lt;survey&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;starttime&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;vdate&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldname = &apos;clinicianid&apos; fieldtype = &apos;text&apos;&gt;
        '''		&lt;text&gt;Clinician ID&lt;/text&gt;
        '''		&lt;maxCharacters&gt;80&lt;/maxCharacters&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldname = &apos;clinicianid2&apos; fieldtype = &apos;text&apos;&gt;
        '''		&lt;text&gt;Clinician ID&lt;/text&gt;
        '''		&lt;maxChar [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property htn_lab() As String
            Get
                Return ResourceManager.GetString("htn_lab", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version = &apos;1.0&apos; encoding = &apos;utf-8&apos;?&gt;
        '''&lt;survey&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;starttime&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;vdate&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldname = &apos;intvinit&apos; fieldtype = &apos;text_integer&apos;&gt;
        '''		&lt;text&gt;Enter your Interviewer ID&lt;/text&gt;
        '''		&lt;maxCharacters&gt;2&lt;/maxCharacters&gt;
        '''		&lt;numeric_check&gt;
        '''			&lt;values minvalue =&apos;1&apos; maxvalue=&apos;99&apos; other_values = &apos;1&apos; message = &apos;Number must be betwee [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property leap() As String
            Get
                Return ResourceManager.GetString("leap", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version = &apos;1.0&apos; encoding = &apos;utf-8&apos;?&gt;
        '''&lt;survey&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;starttime&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;vdate&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldname = &apos;intvinit&apos; fieldtype = &apos;text_integer&apos;&gt;
        '''		&lt;text&gt;Enter your Interviewer ID&lt;/text&gt;
        '''		&lt;maxCharacters&gt;2&lt;/maxCharacters&gt;
        '''		&lt;numeric_check&gt;
        '''			&lt;values minvalue =&apos;1&apos; maxvalue=&apos;99&apos; other_values = &apos;1&apos; message = &apos;Number must be between 1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property leap_screen() As String
            Get
                Return ResourceManager.GetString("leap_screen", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version = &apos;1.0&apos; encoding = &apos;utf-8&apos;?&gt;
        '''&lt;survey&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;starttime&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldname = &apos;intvinit&apos; fieldtype = &apos;text_integer&apos;&gt;
        '''		&lt;text&gt;Enter your Interviewer ID&lt;/text&gt;
        '''		&lt;maxCharacters&gt;3&lt;/maxCharacters&gt;
        '''		&lt;numeric_check&gt;
        '''			&lt;values minvalue =&apos;1&apos; maxvalue=&apos;100&apos; other_values = &apos;1&apos; message = &apos;Number must be between 1 and 100!&apos;&gt;&lt;/values&gt;
        '''		&lt;/numeric_check&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldna [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property move() As String
            Get
                Return ResourceManager.GetString("move", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property na() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("na", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property next1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notdone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notdone", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version = &apos;1.0&apos; encoding = &apos;utf-8&apos;?&gt;
        '''&lt;survey&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;starttime&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldname = &apos;card_number&apos; fieldtype = &apos;text_integer&apos;&gt;
        '''		&lt;text&gt;Serial number of recruitment card distributed&lt;/text&gt;
        '''		&lt;maxCharacters&gt;6&lt;/maxCharacters&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;radio&apos; fieldname = &apos;sex&apos; fieldtype = &apos;integer&apos;&gt;
        '''		&lt;text&gt;Sex of person to whom recruitment card distributed&lt;/text&gt;
        '''		&lt;responses&gt;
        '''			&lt;respons [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property opal_card() As String
            Get
                Return ResourceManager.GetString("opal_card", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property previous1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previous1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version = &apos;1.0&apos; encoding = &apos;utf-8&apos;?&gt;
        '''&lt;survey&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;starttime&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;vdate&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldname = &apos;intvinit&apos; fieldtype = &apos;text_integer&apos;&gt;
        '''		&lt;text&gt;Enter your Interviewer ID&lt;/text&gt;
        '''		&lt;maxCharacters&gt;2&lt;/maxCharacters&gt;
        '''		&lt;numeric_check&gt;
        '''			&lt;values minvalue =&apos;1&apos; maxvalue=&apos;99&apos; other_values = &apos;1&apos; message = &apos;Number must be between 1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property reach_hiv() As String
            Get
                Return ResourceManager.GetString("reach_hiv", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
