'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ibis_megastudy_pilot.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version = &apos;1.0&apos; encoding = &apos;utf-8&apos;?&gt;
        '''&lt;survey&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;starttime&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;radio&apos; fieldname = &apos;countrycode&apos; fieldtype = &apos;integer&apos;&gt;
        '''		&lt;text&gt;Select The country/region&lt;/text&gt;
        '''		&lt;responses&gt;
        '''			&lt;response value = &apos;1&apos;&gt;Uganda&lt;/response&gt;
        '''			&lt;response value = &apos;2&apos;&gt;Kenya&lt;/response&gt;
        '''		&lt;/responses&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;text&apos; fieldname = &apos;tabletnum&apos; fieldtype = &apos;text_integer&apos;&gt;
        '''		&lt;text&gt;Please enter the tab [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property baseline() As String
            Get
                Return ResourceManager.GetString("baseline", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property done() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("done", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eye() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eye", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version = &apos;1.0&apos; encoding = &apos;utf-8&apos;?&gt;
        '''&lt;survey&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;starttime&apos; fieldtype = &apos;datetime&apos;&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;radio&apos; fieldname = &apos;countrycode&apos; fieldtype = &apos;integer&apos;&gt;
        '''		&lt;text&gt;Select The country/region&lt;/text&gt;
        '''		&lt;responses&gt;
        '''			&lt;response value = &apos;1&apos;&gt;Uganda&lt;/response&gt;
        '''			&lt;response value = &apos;2&apos;&gt;Kenya&lt;/response&gt;
        '''		&lt;/responses&gt;
        '''	&lt;/question&gt;
        '''
        '''
        '''	&lt;question type = &apos;automatic&apos; fieldname = &apos;subjid&apos; fieldtype = &apos;text&apos;&gt;
        '''		&lt;maxCharacters&gt;20&lt;/maxCharacters [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property followup() As String
            Get
                Return ResourceManager.GetString("followup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lucky_spin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lucky_spin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property na() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("na", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property next1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notdone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notdone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property previous1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previous1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property spin_12315_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spin_12315_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
